Develop
rob3n/yard-frontend pull request #1
Opened 2017-06-26 14:43 UTC by rob3n

по поводу нейминга примерно так? может где то не соответствуют классы,

2017-06-26 17:35 UTC, evgenyrodionov commented
Сначала доделай, потом вешай ПР

2017-06-26 17:35 UTC, evgenyrodionov commented
Коммиты хуевые

2017-06-26 17:36 UTC, evgenyrodionov commented
Перечитай телеграф, там описано как коммитить

2017-06-26 17:46 UTC, kostyalucker commented
Все услышал

26 июня 2017 г. 8:39 PM пользователь "Evgeny Rodionov" <
notifications@github.com> написал:

> Сначала доделай, потом вешай ПР
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rob3n/yard-frontend/pull/1#issuecomment-311128736>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AZz5KGjlq4zMf-pnSN2Xl8J4V5NZ3qGyks5sH-y1gaJpZM4OFaOL>
> .
>

2017-06-27 14:27 UTC, imevro requested changes

2017-06-27 14:27 UTC, evgenyrodionov commented on complex.html
> +    <header class="header">
почему тут 4 пробела

2017-06-27 14:27 UTC, evgenyrodionov commented on complex.html
> +  <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,700,900" rel="stylesheet">
почему два подключения шрифтов и куда ты потерял протокол http

2017-06-27 17:20 UTC, imevro requested changes

2017-06-27 17:20 UTC, evgenyrodionov commented on complex.html
> +          <a class="header-nav-link" href="#">
отступы

2017-06-27 17:20 UTC, evgenyrodionov commented on complex.html
> +          <a class="header-nav-link" href="#">
приведи в порядок

2017-06-28 10:26 UTC, imevro requested changes

2017-06-28 10:26 UTC, evgenyrodionov commented on complex.html
> +              Купить
все еще не понял почему я должен проверять если тут 4 пробела отступ

2017-06-28 14:13 UTC, imevro requested changes

2017-06-28 14:13 UTC, evgenyrodionov commented on complex.html
> +      <div class="compass-cards-wrap">
зачем этот враппер

2017-06-28 14:13 UTC, evgenyrodionov commented on complex.html
> +          <div class="compass-card">
зачем этот враппер

2017-06-29 10:39 UTC, imevro submitted a review, later dismissed

2017-06-29 10:39 UTC, evgenyrodionov commented on complex.html
> +        <div class="compass-card">
а этот враппер зачем?

2017-06-29 16:08 UTC, rob3n commented
небольшие отклонения только в футере, надеюсь не критично, по сетке все понял

2017-06-29 17:14 UTC, rob3n commented
Переименовал файл разметки

2017-06-29 21:09 UTC, evgenyrodionov commented
https://rawgit.com/rob3n/yard-frontend/develop/complexes.html

![image](https://user-images.githubusercontent.com/775692/27710351-17e40db0-5d28-11e7-98b8-8ed57895f98a.png)
![image](https://user-images.githubusercontent.com/775692/27710368-257ec53c-5d28-11e7-8e1e-b8cec981f44a.png)
![image](https://user-images.githubusercontent.com/775692/27710387-3b180fd4-5d28-11e7-8f04-2836c5c444af.png)

2017-06-30 09:34 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27729932-4a929796-5d90-11e7-9662-0b8ee4e2f5fe.png)
![image](https://user-images.githubusercontent.com/775692/27729937-5157a08a-5d90-11e7-901f-e7078a0e6cab.png)
![image](https://user-images.githubusercontent.com/775692/27729973-64ae2140-5d90-11e7-87f4-0e2ace8d069d.png)

2017-06-30 12:57 UTC, rob3n commented
делаю по pixel perfect в chrome, там совпадает практически все

2017-06-30 14:02 UTC, imevro requested changes
у кнопки контакт зе тим лишний бордер
бэкграундные точки слишком большие
цвет бэкграунда не тот
какой-то непонятный паддинг у бади, подключи нормалайз

2017-06-30 15:36 UTC, rob3n commented
картинка body оригинальная, которую ты скидывал, не знаю что с ней сделать чтобы меньше стала

2017-06-30 19:02 UTC, rob3n commented
сделал background size 1.5%

2017-06-30 19:35 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27751337-7a1c085e-5de4-11e7-8b7b-6cbc515686ac.png)

2017-06-30 21:33 UTC, evgenyrodionov commented
Футер не доделан

2017-06-30 21:34 UTC, imevro requested changes
↑

2017-07-01 09:31 UTC, imevro requested changes

2017-07-01 09:31 UTC, evgenyrodionov commented on style.css
> +.compass-contact-wrap p {
мы не вешаем стили на теги

2017-07-01 09:31 UTC, evgenyrodionov commented on style.css
> +  margin-top: -.2rem;
мы не используем отрицательные марджины

2017-07-01 09:31 UTC, evgenyrodionov commented on style.css
> +.footer-contacts-title:nth-child(1) {
это что вообще

2017-07-01 09:31 UTC, evgenyrodionov commented on style.css
> +.footer .col-xs-2:nth-child(2),.footer .col-xs-2:nth-child(3) {
зачем втф

2017-07-01 09:31 UTC, evgenyrodionov commented on style.css
> +* {
нет, мы не используем такой селектор никогда

2017-07-01 09:31 UTC, evgenyrodionov commented on complexes.html
> +          <div class="ooter-line"></div>
Есть hr, нейминг плохой

2017-07-02 22:56 UTC, imevro approved these changes

2017-07-06 09:44 UTC, merged