Complex page
rob3n/yard-frontend pull request #3
Opened 2017-06-29 20:52 UTC by rob3n

2017-06-29 21:32 UTC, evgenyrodionov commented
с файлами дичь у тебя

2017-06-29 21:32 UTC, evgenyrodionov commented
почему тут не исправил complexes на complex

2017-06-30 11:05 UTC, rob3n commented
долго разбирался с файлами что где, вроде бы все устаканил

2017-06-30 21:45 UTC, evgenyrodionov commented
https://rawgit.com/rob3n/yard-frontend/complex-page/complex-page.html

![image](https://user-images.githubusercontent.com/775692/27755087-4dcd32b6-5df6-11e7-8c63-5a32f427dc37.png)
![image](https://user-images.githubusercontent.com/775692/27755097-56c21904-5df6-11e7-9985-d64e0e8a0f33.png)
![image](https://user-images.githubusercontent.com/775692/27755107-65dafa96-5df6-11e7-96a9-8032219689f6.png)
![image](https://user-images.githubusercontent.com/775692/27755124-71efc604-5df6-11e7-98f9-3cb248b4910f.png)
![image](https://user-images.githubusercontent.com/775692/27755135-84473968-5df6-11e7-8907-bce1bd9577d2.png)

2017-07-01 09:48 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27760914-3d127110-5e5b-11e7-83f7-7a7534f447e4.png)
![image](https://user-images.githubusercontent.com/775692/27760918-49b8c28e-5e5b-11e7-99f1-a9aa780d2160.png)
![image](https://user-images.githubusercontent.com/775692/27760924-5448f26e-5e5b-11e7-978f-5bc987b75cc7.png)
![image](https://user-images.githubusercontent.com/775692/27760929-60f15c90-5e5b-11e7-9bc7-fd799fbc6f42.png)
![image](https://user-images.githubusercontent.com/775692/27760934-83cd7370-5e5b-11e7-9ad6-1920612a9931.png)

2017-07-02 22:59 UTC, imevro requested changes
в телеграме скрины, плюс вынеси общие стили для хедера и футера в styles.css

2017-07-04 23:26 UTC, rob3n commented
Поменял линк на шрифты для адекватного отображения, проверил код, поработал дополнительно с паддингами

2017-07-05 11:22 UTC, rob3n commented
заметил что нет отступа, исправлю

2017-07-05 18:08 UTC, imevro requested changes

2017-07-05 18:08 UTC, evgenyrodionov commented on complex-page.css
> +  width: 583px;
нет

2017-07-05 18:08 UTC, evgenyrodionov commented on complex-page.css
> +/*=============COMPLEXES-ADDReSS===============*/
ЧтО туТ пРоиСхОдиТ

2017-07-05 18:10 UTC, evgenyrodionov commented
И по дизайну в телеграме куча правок

2017-07-05 19:01 UTC, rob3n commented
все исправлено по макету

2017-07-05 21:29 UTC, imevro requested changes

2017-07-05 21:29 UTC, evgenyrodionov commented on complex-page.css
> +.complexes-guide {
с хуя ли во множественном числе?

2017-07-05 21:29 UTC, evgenyrodionov commented on complex-page.css
> +.address-point-title {
выше у тебя было complexes-address-point, сейчас address-point-title. Втф?

2017-07-05 21:29 UTC, evgenyrodionov commented on complex-page.css
> +.address-map-img {
Где консистентность вообще?

2017-07-06 08:53 UTC, rob3n commented
По непонятным причинам rawgit не отображает нормально страницу

2017-07-06 09:44 UTC, merged