Convert pages in components with React
rob3n/yard-frontend pull request #4
Opened 2017-07-06 20:16 UTC by rob3n

2017-07-06 20:17 UTC, rob3n commented
сделал первую страницу, жду комментариев и делаю вторую

2017-07-06 22:09 UTC, rob3n commented
Не проставил расширения в app.js в путях до компонентов

2017-07-06 23:57 UTC, imevro requested changes
дальше не проверял, потому что чужие пры надо читать. 

поставь преттир, а то доебусь до отступов опять

2017-07-06 23:57 UTC, evgenyrodionov commented on package.json
> +  "name": "react-app",
читай чужие пры

2017-07-06 23:57 UTC, evgenyrodionov commented on src/App.js
> +import header from './header';
компоненты с большой буквы, иначе непонятно у тебя хтмл-тег или компонент

2017-07-07 08:05 UTC, rob3n commented
Поправил первую страницу и сделал сразу вторую, разбираюсь с роутингом

2017-07-07 09:59 UTC, rob3n commented
в стилях не поменял class на className исправил но пока не пушу

2017-07-07 11:09 UTC, imevro requested changes
оно же не работает

2017-07-07 17:08 UTC, imevro requested changes

2017-07-07 17:08 UTC, evgenyrodionov commented on public/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
читай чужие пры

2017-07-07 20:47 UTC, rob3n commented
Смотрел ПРы, подключил через npm, жду одобрения делать дальше

2017-07-07 21:31 UTC, rob3n commented
в Cards.js ошибка district присваивал значение, исправил на location чтобы отображалось, закоммитил

2017-07-07 21:32 UTC, imevro requested changes

2017-07-07 21:32 UTC, evgenyrodionov commented on package.json
> +    "style-loader": "^0.18.2"
не понял зачем

2017-07-07 21:32 UTC, evgenyrodionov commented on src/Complexes/Show/InfoItem.js
> +    <div>
а зачем тут див

2017-07-07 21:32 UTC, evgenyrodionov commented
Дальше не проверял, раз ты не закончил

2017-07-07 21:32 UTC, evgenyrodionov commented
Охуенно удобно проверять когда прилетают коммиты на ходу

2017-07-08 10:49 UTC, imevro requested changes

2017-07-08 10:49 UTC, evgenyrodionov commented on src/App.js
> +import Header from './Header.js';
читай чужие пры

2017-07-08 10:49 UTC, evgenyrodionov commented on src/Complexes/List/Card.js
> +      <Link className="compass-card-link" to='/complex'>
поставь преттир, что за мешанина из двойных кавычек и одинарных

2017-07-08 10:49 UTC, evgenyrodionov commented on src/Complexes/List/Cards.js
> +        text="The Lewis Steel Building is a masterful industrial conversion located in
реал, читай чужие пры

2017-07-08 17:27 UTC, imevro requested changes

2017-07-08 17:27 UTC, evgenyrodionov commented on src/Complexes/List/Card.js
> +import cardimg from "../../img/bitmap.jpg";
положи в паблик и используй оттуда, это не интерфейсное изображение поэтому нет смысла его использовать как модуль

2017-07-08 17:27 UTC, evgenyrodionov commented on src/Complexes/List/index.js
> +import Cards from "./Cards";
читай чужие пры

2017-07-08 17:27 UTC, evgenyrodionov commented on src/Complexes/Show/OffersCard.js
> +            {props.nameFirst}
это статические данные, используй прямо тут

2017-07-08 17:27 UTC, evgenyrodionov commented on src/Complexes/Show/OffersCard.js
> +          {props.valueFirst}
тупой нейминг, передавай осмысленно площадь

2017-07-08 21:43 UTC, imevro requested changes

2017-07-08 21:43 UTC, evgenyrodionov commented on src/Complexes/Show/Guide.js
> +    <div>
с хуя ли дивом стало?

2017-07-08 21:43 UTC, evgenyrodionov commented on src/Complexes/Show/Guide.js
> +    <div>
в конце концов нахуя он в принципе нужен?

2017-07-08 21:43 UTC, evgenyrodionov commented on src/Complexes/Show/Info.js
> +          <small className="complex-info-subheading">предложений</small>
что за невнимательность

2017-07-08 21:43 UTC, evgenyrodionov commented on src/Complexes/Show/Offers.js
> +            area="от 59 до 120 м²"
читай чужие пуллреквесты

2017-07-08 21:43 UTC, evgenyrodionov commented on src/Complexes/Show/index.js
> +        offers="950"
почему строкой

2017-07-08 21:54 UTC, rob3n commented on src/Complexes/Show/Guide.js
> +    <div>
потому что это две секции у меня были, я сделал в один компонент чтобы сохранить стили все

2017-07-09 22:11 UTC, imevro approved these changes

2017-07-09 22:13 UTC, merged