Styled components
rob3n/yard-frontend pull request #5
Opened 2017-07-08 16:47 UTC by rob3n

2017-07-08 17:32 UTC, imevro requested changes
дальше не проверяю

2017-07-08 17:32 UTC, evgenyrodionov commented on src/Complexes/List/Card.js
> + width: 484px;
отступов нет

2017-07-08 21:46 UTC, imevro requested changes
пиздец, чисти репозиторий от конфликтов

2017-07-09 17:30 UTC, rob3n commented
не то запушил случайно, поэтому убрал и заново поставил ПР

2017-07-09 22:13 UTC, imevro approved these changes

2017-07-09 22:13 UTC, merged