Eslint, husky, deploy
rob3n/yard-frontend pull request #6
Opened 2017-07-11 15:03 UTC by rob3n

https://build-osbhdovkgl.now.sh/

2017-07-11 17:36 UTC, imevro requested changes

2017-07-11 17:36 UTC, evgenyrodionov commented on src/index.js
> +/* eslint-disable no-undef */
нет

2017-07-11 20:29 UTC, rob3n commented
https://build-vwawgqgagp.now.sh/complex

2017-07-11 21:49 UTC, imevro requested changes

2017-07-11 21:49 UTC, evgenyrodionov commented on .eslintrc.json
> +      "jest": true,
поч 4 пробела!!!

2017-07-12 07:29 UTC, rob3n commented
https://build-rfigbzsovh.now.sh/

2017-07-12 12:41 UTC, imevro approved these changes

2017-07-12 12:42 UTC, merged